#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

# $Id: Settings.yaml 3480 2009-11-19 16:45:21Z robert $

