#                                                                        #
# Settings Configuration for the Admin package                           #
#                                                                        #

Admin:
  Models: [] 
#    - \F3\Blog\Domain\Model\Blog
#    - \F3\Blog\Domain\Model\Post
#    - \F3\Blog\Domain\Model\Category
  Defaults:
    newinlines: 3
  Adapters:
    F3\Admin\Adapters\PHPCRAdapter: active
    F3\Admin\Adapters\DummyAdapter: active
  Fallbacks:
    Views:
      - resource://@package/Private/Templates/@being/@action/@variant.html
      - resource://@package/Private/Templates/Admin/@action/@variant.html
      - resource://@package/Private/Templates/@being/@action.html
      - resource://@package/Private/Templates/Admin/@action.html
      - resource://Admin/Private/Templates/Standard/@action/@variant.html
      - resource://Admin/Private/Templates/Standard/@action.html
    Partials:
      - resource://@package/Private/Partials/@being/@action.html
      - resource://@package/Private/Partials/@action.html
      - resource://Admin/Private/Partials/@action.html
    Actions:
      - resource://@package/Private/Partials/@being/Actions/@action.html
      - resource://@package/Private/Partials/Actions/@action.html
      - resource://Admin/Private/Partials/Actions/@action.html
    Widgets:
      - resource://@package/Private/Partials/@being/Widgets/@partial.html
      - resource://@package/Private/Partials/Widgets/@partial.html
      - resource://Admin/Private/Partials/Widgets/@partial.html
PHPCR:
  Widgets:
    Mapping:
      string:   Textfield
      readonly:   TextfieldReadonly
      integer:  Spinner
      float:    Textfield
      boolean:  Boolean
      \F3\FLOW3\Resource\Resource: Upload
#      \DateTime: DateTime
      ^\\*F3\\[A-Za-z]+\\Domain\\Model\\[A-Za-z]+$: SingleRelation
      ^\\*\SplObjectStorage\<\\*F3\\[A-Za-z]+\\Domain\\Model\\[A-za-z]+>$: MultipleRelation
  Conversions:
    Storage:
      \DateTime: this->stringToDateTime
      ^\\F3\\[A-Za-z]+\\Domain\\Model\\[A-Za-z]+$: this->identifierToModel
 #     ^\\\SplObjectStorage\<\\*F3\\[A-Za-z]+\\Domain\\Model\\[A-za-z]+>$: this->identifiersToSplObjectStorage
    Presentation:
      \DateTime: this->dateTimeToString
      ^\\*F3\\[A-Za-z]+\\Domain\\Model\\[A-Za-z]+$: this->modelToIdentifier
      ^\\*\SplObjectStorage\<\\*F3\\[A-Za-z]+\\Domain\\Model\\[A-za-z]+>$: this->splObjectStorageToIdentifiers

Dummy:
  DataStorage: '%FLOW3_PATH_DATA%Persistent/DummyData'
  Widgets:
    Mapping:
      string:   Textfield
      readonly: TextfieldReadonly
      integer:  Spinner
      float:    Textfield
      boolean:  Boolean
      resource: Upload
  #      \DateTime: DateTime
      ^\\*Being\\([A-Za-z]+)$: SingleRelation
      ^\\*Beings\\([A-za-z]+)$: MultipleRelation
  Conversions:
    Storage:
      ^\\*Being\\([A-Za-z]+)$: this->getId
      ^\\*Beings\\([A-za-z]+)$: this->beingsToIdentifiers
    Presentation:
      ^\\*Being\\([A-Za-z]+)$: this->identifierToBeing
      ^\\*Beings\\([A-za-z]+)$: this->identifiersToBeings
  Beings:
    Tag:
      properties:
        title:
          type:string 
    Widgets:
      properties:
        string:
          type:string
        integer:
          type:integer
        float:
          type:float
        boolean:
          type:boolean
#        resource:
#          type:resource
        singleRelation:
          type: \Being\Tag
        multipleRelation:
          type: \Beings\Tag
    Options:
      properties:
        ingoredField:
          type: string
          ignore: true
          infotext: This field will be ignored by autoadmin
        specificWidget:
          type: string
          widget: TextArea
          infotext: This field has a Textarea specified as Widget
        specificLabel:
          type: string
          label: Specific Label
          infotext: This field has a label set to override the internal name
    Sets:
      set:
        - First Set (string,integer,float,boolean)
        - Second Set (string2,integer2,float2,boolean2)
      properties:
        string:
          type:string
        integer:
          type:integer
        float:
          type:float
        boolean:
          type:boolean
        string2:
          type:string
        integer2:
          type:integer
        float2:
          type:float
        boolean2:
          type:boolean