#                                                                        #
# Settings Configuration for the Admin package                           #
#                                                                        #

Admin:
  Models: []
  Defaults:
    newinlines: 3
  Adapters:
    F3\Admin\Adapters\PHPCRAdapter: active
  Fallbacks:
    Views:
      - package://@package/Private/Templates/@model/@action/@variant.html
      - package://@package/Private/Templates/Admin/@action/@variant.html
      - package://@package/Private/Templates/@model/@action.html
      - package://@package/Private/Templates/Admin/@action.html
      - package://Admin/Private/Templates/Standard/@action/@variant.html
      - package://Admin/Private/Templates/Standard/@action.html
    Widgets:
      - package://@group/Private/Templates/@being/Widgets/@partial.html
      - package://@group/Private/Templates/Widgets/@partial.html
      - package://Admin/Private/Templates/Standard/Widgets/@partial.html
PHPCR:
  Widgets:
    Mapping:
      string:   Textfield
      integer:  Spinner
      float:    Textfield
      boolean:  Checkbox
      \F3\FLOW3\Resource\Resource: Upload
      \DateTime: DateTime
      ^\\F3\\[A-Za-z]+\\Domain\\Model\\[A-Za-z]+$: SingleRelation
      ^\\\SplObjectStorage\<\\*F3\\[A-Za-z]+\\Domain\\Model\\[A-za-z]+>$: MultipleRelation