#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

# $Id: Routes.yaml 3886 2010-02-28 17:03:50Z robert $


-
  name: 'Admin actions 1'
  uriPattern: 'admin/{@action}'
  defaults:
    '@package':    'Admin'
    '@controller': 'Standard'
    '@format':     'html'