#                                                                        #
# Settings Configuration for the Admin package                           #
#                                                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          AdminProvider:
            providerClass: Admin\Security\AdminProvider
            entryPoint:
              WebRedirect:
                uri: admin/login/index
      authorization:
        # An array of access decision voters that should vote when access decisions are made
        accessDecisionVoters:
          - Admin\Security\Voter\Policy
          - TYPO3\FLOW3\Security\Authorization\Voter\Policy
Admin:
  Beings: []
  PageTitle: Admin
  DemoMode: False
  FlushCacheInDevelopment: true
  Logging:
    Active: true
    Ignore: 
      - index
      - list
      - view
  ViewSettings:
    List:
      Limits:
        - 10
        - 20
        - 100
        - 1000
        - 10000
      Default: 20
      MaxPages: 9
  Navigation:
    Top:
      Documentation:
        Arguments:
          action: index
          controller: doc
          package: admin
  Defaults:
    Variant: Default
    properties:
      OptionsProvider: Admin\OptionsProvider\RelationOptionsProvider
      Representation:
        DateFormat: Y-m-d
        DateJsFormat: yyyy-MM-dd
        DateTimeFormat: Y-m-d
  Adapters:
    Admin\Adapters\DoctrineAdapter: active
  ConfigurationProvider:
    - Admin\ConfigurationProvider\DefaultsConfigurationProvider
    - Admin\ConfigurationProvider\AnnotationConfigurationProvider
    - Admin\ConfigurationProvider\YamlConfigurationProvider
  Fallbacks:
    Views:
      - resource://@package/Private/Templates/@being/@action/@variant.html
      - resource://@package/Private/Templates/Admin/@action/@variant.html
      - resource://@package/Private/Templates/@being/@action.html
      - resource://@package/Private/Templates/Admin/@action.html
      - resource://Admin/Private/Templates/Standard/@action/@variant.html
      - resource://Admin/Private/Templates/Standard/@action.html
    Partials:
      - resource://@package/Private/Partials/@being/@action/@partial/@variant.html
      - resource://@package/Private/Partials/@being/@action/@partial.html
      - resource://@package/Private/Partials/@being/@partial/@variant.html
      - resource://@package/Private/Partials/@being/@partial.html
      - resource://@package/Private/Partials/@action/@partial/@variant.html
      - resource://@package/Private/Partials/@action/@partial.html
      - resource://@package/Private/Partials/@partial/@variant.html
      - resource://@package/Private/Partials/@partial.html
      - resource://Admin/Private/Partials/@action/@partial.html
      - resource://Admin/Private/Partials/@action/@partial/@variant.html
      - resource://Admin/Private/Partials/@partial/@variant.html
      - resource://Admin/Private/Partials/@partial.html
      - resource://Admin/Private/Partials/@partial/Default.html
    DashboardWidgets:
      - resource://@package/Private/Partials/@being/DashboardWidgets/@partial.html
      - resource://@package/Private/Partials/DashboardWidgets/@partial.html
      - resource://Admin/Private/Partials/DashboardWidgets/@partial.html
    Widgets:
      - resource://@package/Private/Partials/@being/Widgets/@partial.html
      - resource://@package/Private/Partials/Widgets/@partial.html
      - resource://Admin/Private/Partials/Widgets/@partial.html
  Mapping:
    Widgets:
      string:   Textfield
      readonly:   TextfieldReadonly
      integer:  Spinner
      float:    Textfield
      boolean:  Boolean
      \TYPO3\FLOW3\Resource\Resource: Upload
      \DateTime: DateJs
      ^\\[A-Za-z0-9\\]+\\Domain\\Model\\[A-Za-z]+$: Chosen
      ^\\[A-Za-z0-9\\]+\\Security\\[A-Za-z]+$: Chosen
      ^\\Doctrine\\Common\\Collections\\Collection\<\\[A-Za-z0-9\\]+\\Domain\\Model\\[A-za-z]+>$: MultipleRelation
      ^\\Doctrine\\Common\\Collections\\Collection\<\\[A-Za-z0-9\\]+\\Security\\[A-za-z]+>$: MultipleRelation