#                                                                        #
# Settings Configuration for the Admin package                           #
#                                                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          AdminProvider:
            providerClass: Admin\Security\AdminProvider
            entryPoint:
              WebRedirect:
                uri: admin/login/
      authorization:
        # An array of access decision voters that should vote when access decisions are made
        accessDecisionVoters:
          - Admin\Security\Voter\Policy
          - TYPO3\FLOW3\Security\Authorization\Voter\Policy
Admin:
  PageTitle: Admin
  NavBar: 
    Models:
      Controller: standard
      Action: index
      Children:
        Logout:
          Controller: login
          Action: logout
    Docs:
      Controller: doc
      Action: index
    System:
      Controller: system
      Action: index
  Logging:
    Active: true
    Ignore: 
      - index
      - list
      - view
  Defaults:
      properties:
        optionsprovider: Admin\OptionsProvider\RelationOptionsProvider
  Adapters:
    Admin\Adapters\DoctrineAdapter: active
#    Admin\Adapters\DummyAdapter: active
  Fallbacks:
    Views:
      - resource://@package/Private/Templates/@being/@action/@variant.html
      - resource://@package/Private/Templates/Admin/@action/@variant.html
      - resource://@package/Private/Templates/@being/@action.html
      - resource://@package/Private/Templates/Admin/@action.html
      - resource://Admin/Private/Templates/Standard/@action/@variant.html
      - resource://Admin/Private/Templates/Standard/@action.html
    Partials:
      - resource://@package/Private/Partials/@being/@action/@partial.html
      - resource://@package/Private/Partials/@being/@partial.html
      - resource://@package/Private/Partials/@action/@partial.html
      - resource://@package/Private/Partials/@partial.html
      - resource://Admin/Private/Partials/@action/@partial.html
      - resource://Admin/Private/Partials/@partial.html
    DashboardWidgets:
      - resource://@package/Private/Partials/@being/DashboardWidgets/@partial.html
      - resource://@package/Private/Partials/DashboardWidgets/@partial.html
      - resource://Admin/Private/Partials/DashboardWidgets/@partial.html
    Widgets:
      - resource://@package/Private/Partials/@being/Widgets/@partial.html
      - resource://@package/Private/Partials/Widgets/@partial.html
      - resource://Admin/Private/Partials/Widgets/@partial.html

Doctrine:
  Beings: []
  ConfigurationProvider:
    - Admin\ConfigurationProvider\DefaultsConfigurationProvider
    - Admin\ConfigurationProvider\ReflectionConfigurationProvider
    - Admin\ConfigurationProvider\YamlConfigurationProvider
  Widgets:
    Mapping:
      string:   Textfield
      readonly:   TextfieldReadonly
      integer:  Spinner
      float:    Textfield
      boolean:  Boolean
      \TYPO3\FLOW3\Resource\Resource: Upload
      \DateTime: DateTime
      ^\\[A-Za-z0-9\\]+\\Domain\\Model\\[A-Za-z]+$: SingleRelation
      ^\\[A-Za-z0-9\\]+\\Security\\[A-Za-z]+$: SingleRelation
      ^\\Doctrine\\Common\\Collections\\Collection\<\\[A-Za-z0-9\\]+\\Domain\\Model\\[A-za-z]+>$: MultipleRelation
      ^\\Doctrine\\Common\\Collections\\Collection\<\\[A-Za-z0-9\\]+\\Security\\[A-za-z]+>$: MultipleRelation
      
Dummy:
  DataStorage: '%FLOW3_PATH_DATA%Persistent/DummyData'
  ConfigurationProvider:
    - Admin\ConfigurationProvider\YamlConfigurationProvider
  Defaults:
      properties:
        optionsProvider: Admin\OptionsProvider\RelationOptionsProvider
  Widgets:
    Mapping:
      # Pattern (Text or Regex)          Widget
      string:   Textfield
      readonly: TextfieldReadonly
      integer:  Spinner
      float:    Textfield
      boolean:  Boolean
      resource: Upload
      ^\\*Being\\([A-Za-z]+)$: SingleRelation
      ^\\*Beings\\([A-za-z]+)$: MultipleRelation
  Beings:
    Relation:
      properties:
        singleRelation:
          type: \Being\Tag
        multipleRelation:
          type: \Beings\Tag
    Tag:
      properties:
        title:
          type: string 
    Widgets:
      properties:
        string:
          type: string
        integer:
          type: integer
        float:
          type: float
        boolean:
          type: boolean
#        resource:
#          type:resource
        singleRelation:
          type: \Being\Tag
        multipleRelation:
          type: \Beings\Tag
    Options:
      properties:
        ingoredField:
          type: string
          ignore: true
          infotext: This field will be ignored by autoadmin
        specificWidget:
          type: string
          widget: TextArea
          infotext: This field has a Textarea specified as Widget
        specificLabel:
          type: string
          label: Specific Label
          infotext: This field has a label set to override the internal name
    Sets:
      set:
        - First Set (string,integer,float,boolean)
        - Second Set (string2,integer2,float2,boolean2)
      properties:
        string:
          type:string
        integer:
          type:integer
        float:
          type:float
        boolean:
          type:boolean
        string2:
          type:string
        integer2:
          type:integer
        float2:
          type:float
        boolean2:
          type:boolean
